version: '3.3'
services:
  node:
    build:
      context: node
    command: bash -c "npm start"
    ports:
      - "8080:8080"
    networks:
      - node-network
networks:
  node-network:
    driver: bridge 


